let imgModelos = [
  { marca: "Audi", modelo: "A1", img: "../imagenes/Audi-A1.jpeg" },
  { marca: "Audi", modelo: "A3", img: "../imagenes/Audi-A3.jpeg" },
  { marca: "Audi", modelo: "A4", img: "../imagenes/Audi-A4.jpeg" },
  { marca: "Audi", modelo: "A6", img: "../imagenes/Audi-A6.jpeg" },
  { marca: "Audi", modelo: "A8", img: "../imagenes/Audi-A8.jpeg" },
  { marca: "Audi", modelo: "Q2", img: "../imagenes/Audi-Q2.jpeg" },
  { marca: "Audi", modelo: "Q3", img: "../imagenes/Audi-Q3.jpeg" },
  { marca: "Audi", modelo: "Q5", img: "../imagenes/Audi-Q5.jpeg" },
  { marca: "Audi", modelo: "Q8", img: "../imagenes/Audi-Q8.jpeg" },
  { marca: "Volkswagen", modelo: "Gol/Voyage", img: "../imagenes/VW-Gol.jpeg" },
  {
    marca: "Volkswagen",
    modelo: "Polo/virtus",
    img: "../imagenes/VW-Polo.jpeg",
  },
  { marca: "Volkswagen", modelo: "Jetta", img: "../imagenes/vw-jetta.jpeg" },
  { marca: "Volkswagen", modelo: "Golf", img: "../imagenes/VW-golf.jpeg" },
  {
    marca: "Volkswagen",
    modelo: "Cross fox/Fox xtreme",
    img: "../imagenes/VW-foxtrem.jpeg",
  },
  { marca: "Volkswagen", modelo: "T-Cross", img: "../imagenes/VW-t-cross.jpeg" },
  { marca: "Volkswagen", modelo: "Taos", img: "../imagenes/VW-taos.jpeg" },
  { marca: "Volkswagen", modelo: "Tiguan", img: "../imagenes/VW-tigan.jpeg" },
  { marca: "Volkswagen", modelo: "Touareg", img: "../imagenes/VW-touareg.jpeg" },
  { marca: "Volkswagen", modelo: "Amarok", img: "../imagenes/VW-amarok.jpeg" },
  { marca: "Seat", modelo: "Ibiza", img: "../imagenes/SEAT-ibiza.jpeg" },
  { marca: "Seat", modelo: "Cupra", img: "../imagenes/SEAT-cupra.jpeg" },
  { marca: "Seat", modelo: "Leon", img: "../imagenes/SEAT-leon.jpeg" },
  { marca: "Seat", modelo: "Bocanegra", img: "../imagenes/SEAT-bocanegra.jpeg" },
  { marca: "Seat", modelo: "Arona", img: "../imagenes/SEAT-arona.jpeg" },
];
